<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Currency exchange</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="css/pikaday.css">
        <link rel="stylesheet" href="css/styles.css">
    </head>
    <body>
        <h1>Currency</h1>
        <div>exchange rates with PHP and JavaScript</div>

        <?php if (isset($latest['rates'])) : ?>
            <?php if (isset($currencies)): ?>
                <form id="currency-form" method="get">
                    <select id="currency-base-selector" name="base">
                        <?php foreach ($currencies as $currency): ?>
                            <?php $selected = ($currency === $latest['base']) ? 'selected' : '' ?>
                            <option <?= $selected ?>><?= $currency ?></option>
                        <?php endforeach; ?>
                    </select>
                </form>
            <?php endif; ?>
            <input id="datepicker" value="<?= $selectedDate ?>">
            <div id="container"></div>
            <h2>Base Currency: <?= $latest['base'] ?></h2>
            <ul>
            <?php foreach ($latest['rates'] as $currency=>$rate) : ?>
                <li><strong><?= $currency?></strong> <?= $rate ?></li>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/date-fns/1.28.5/date_fns.min.js"></script>
        <script src="js/pikaday.js"></script>
        <script src="js/scripts.js"></script>
    </body>
</html>
